version: 0.2

env:
  variables:
    BACK_HOST: "backend-lb-4e1b9e5842229244.elb.us-east-1.amazonaws.com"
    API_PORT: "3000"
    PORT: "80"

phases:
  build:
    commands:
      - echo Installing dependencies
      - npm install
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
  - '*'